# Nome da aplicação
spring.application.name=inventory-service
# Porta do Servidor Java
server.port=8081

# Conexão com o NOVO Banco (Porta 5434)
spring.datasource.url=jdbc:postgresql://localhost:5434/inventory_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect